/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controladores.ControladorCliente;
import java.awt.Container;
import javax.swing.JFrame;

/**
 *
 * @author Usuario
 */
public class MainFrameCliente extends JFrame{
Container panel;
    private VentanaLogin vistaLogin = new VentanaLogin();
    private VentanaInicioSesion vistaInsesion = new VentanaInicioSesion();
    private VentanaRegistro vistaRegistro = new VentanaRegistro();
    private ControladorCliente controlador ;
    
    public MainFrameCliente() {
        initComponents();
        vistaLogin.setVisible(true);    
    }

    public void setControlador(ControladorCliente c)
    {
        this.controlador = c;
        vistaLogin.setControlador(c);
        vistaInsesion.setControlador(c);
        vistaRegistro.setControlador(c);
    }
    
    public void setLogin()
    {
        vistaLogin.setVisible(true);
        vistaRegistro.setVisible(false);
        vistaInsesion.setVisible(false);
    }
    
    public void setInicioSesion()
    {
        vistaLogin.setVisible(false);
        vistaInsesion.setVisible(true);
    }
    
    public void setRegistro()
    {
        vistaLogin.setVisible(false);
        vistaRegistro.setVisible(true);
    }
    
    public String getNombreUsuario()
    {
        if(vistaRegistro.isVisible())
         return vistaRegistro.getNombreUsuario();
        else
         return vistaInsesion.getNombreUsuario();  
    }
    
    public String getContrasena()
    {
         if(vistaRegistro.isVisible())
         return vistaRegistro.getContrasena();
        else
         return vistaInsesion.getContrasena(); 
    }
    
    public String getNombre()
    {
        return vistaRegistro.getNombre();
    }
    
    public void setDialogError(String mensaje)
    {
        DialogCliente dialog = new DialogCliente(null, true, "Error", mensaje);
        dialog.setVisible(true);
    }
    
    public void setDialogExito(String mensaje)
    {
        DialogCliente dialog = new DialogCliente(null, true, "Exito", mensaje);
        dialog.setVisible(true);
    }
    
    public void setDialogAdv(String mensaje)
    {
        DialogCliente dialog = new DialogCliente(null, true, "Advertencia", mensaje);
        dialog.setVisible(true);
    }
    
    public void setPanel()
    {
        panel = new NewJPanel();
        setContentPane(panel);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
