/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vista;

import javax.swing.JButton;
import java.util.Date;
import java.util.Calendar;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.LocalTime;
/**
 *
 * @author Usuario
 */
public class PanelApp extends VentanaClienteAbstract{

    /**
     * Creates new form PanelApp
     */
    public PanelApp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBotonesMascota = new javax.swing.ButtonGroup();
        grupoBotonEquipaje = new javax.swing.ButtonGroup();
        grupoBotonesZona = new javax.swing.ButtonGroup();
        ScrollPaneInfoViaje = new javax.swing.JScrollPane();
        textAreaInfoViaje = new javax.swing.JTextArea();
        labelInfoViaje = new javax.swing.JLabel();
        labelFormulario = new javax.swing.JLabel();
        botonSIequipaje = new javax.swing.JRadioButton();
        labelMascota = new javax.swing.JLabel();
        labelDistancia = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();
        labelCantPasajeros = new javax.swing.JLabel();
        botonNOequipaje = new javax.swing.JRadioButton();
        labelEquipaje = new javax.swing.JLabel();
        textDistancia = new javax.swing.JTextField();
        botonSImascota = new javax.swing.JRadioButton();
        botonNOmascota = new javax.swing.JRadioButton();
        selectorFecha = new com.toedter.calendar.JDateChooser();
        labelFecha1 = new javax.swing.JLabel();
        botonPeligrosa = new javax.swing.JRadioButton();
        botonSinAsfaltar = new javax.swing.JRadioButton();
        botonEstandar = new javax.swing.JRadioButton();
        ComboBoxCantPax = new javax.swing.JComboBox<>();
        botonPagar = new javax.swing.JButton();
        botonPedirViaje = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(""), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED)));
        setMinimumSize(new java.awt.Dimension(580, 420));
        setPreferredSize(new java.awt.Dimension(580, 420));

        ScrollPaneInfoViaje.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createTitledBorder(""), new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED)));

        textAreaInfoViaje.setColumns(20);
        textAreaInfoViaje.setRows(5);
        textAreaInfoViaje.setFocusable(false);
        ScrollPaneInfoViaje.setViewportView(textAreaInfoViaje);

        labelInfoViaje.setFont(new java.awt.Font("Palatino Linotype", 3, 14)); // NOI18N
        labelInfoViaje.setForeground(new java.awt.Color(255, 255, 255));
        labelInfoViaje.setText("INFORMACION VIAJE");

        labelFormulario.setFont(new java.awt.Font("Palatino Linotype", 3, 14)); // NOI18N
        labelFormulario.setForeground(new java.awt.Color(255, 255, 255));
        labelFormulario.setText("FORMULARIO VIAJE");

        grupoBotonEquipaje.add(botonSIequipaje);
        botonSIequipaje.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        botonSIequipaje.setForeground(new java.awt.Color(255, 255, 255));
        botonSIequipaje.setText("Si");

        labelMascota.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        labelMascota.setForeground(new java.awt.Color(255, 255, 255));
        labelMascota.setText("Mascota");

        labelDistancia.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        labelDistancia.setForeground(new java.awt.Color(255, 255, 255));
        labelDistancia.setText("Distancia");

        labelFecha.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        labelFecha.setForeground(new java.awt.Color(255, 255, 255));
        labelFecha.setText("Fecha");

        labelCantPasajeros.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        labelCantPasajeros.setForeground(new java.awt.Color(255, 255, 255));
        labelCantPasajeros.setText("Cantidad de pasajeros");

        grupoBotonEquipaje.add(botonNOequipaje);
        botonNOequipaje.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        botonNOequipaje.setForeground(new java.awt.Color(255, 255, 255));
        botonNOequipaje.setSelected(true);
        botonNOequipaje.setText("No");

        labelEquipaje.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        labelEquipaje.setForeground(new java.awt.Color(255, 255, 255));
        labelEquipaje.setText("Equipaje");

        textDistancia.setMinimumSize(new java.awt.Dimension(65, 22));
        textDistancia.setPreferredSize(new java.awt.Dimension(65, 22));

        grupoBotonesMascota.add(botonSImascota);
        botonSImascota.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        botonSImascota.setForeground(new java.awt.Color(255, 255, 255));
        botonSImascota.setText("Si");

        grupoBotonesMascota.add(botonNOmascota);
        botonNOmascota.setFont(new java.awt.Font("Palatino Linotype", 0, 12)); // NOI18N
        botonNOmascota.setForeground(new java.awt.Color(255, 255, 255));
        botonNOmascota.setSelected(true);
        botonNOmascota.setText("No");

        selectorFecha.setDateFormatString("d/M/YYYY");

        labelFecha1.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        labelFecha1.setForeground(new java.awt.Color(255, 255, 255));
        labelFecha1.setText("Zona");

        grupoBotonesZona.add(botonPeligrosa);
        botonPeligrosa.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        botonPeligrosa.setForeground(new java.awt.Color(255, 255, 255));
        botonPeligrosa.setText("peligrosa");

        grupoBotonesZona.add(botonSinAsfaltar);
        botonSinAsfaltar.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        botonSinAsfaltar.setForeground(new java.awt.Color(255, 255, 255));
        botonSinAsfaltar.setText("sin asfaltar");

        grupoBotonesZona.add(botonEstandar);
        botonEstandar.setFont(new java.awt.Font("Palatino Linotype", 1, 12)); // NOI18N
        botonEstandar.setForeground(new java.awt.Color(255, 255, 255));
        botonEstandar.setSelected(true);
        botonEstandar.setText("estandar");

        ComboBoxCantPax.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));

        botonPagar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonPagar.setText("PAGAR");
        botonPagar.setActionCommand("PAGAR VIAJE");
        botonPagar.setEnabled(false);

        botonPedirViaje.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        botonPedirViaje.setText("PEDIR VIAJE");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(ScrollPaneInfoViaje, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelFecha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(selectorFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelDistancia)
                                    .addComponent(labelCantPasajeros))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(textDistancia, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(46, 46, 46))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(ComboBoxCantPax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addContainerGap())))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelFecha1)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(botonEstandar)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(botonPeligrosa)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(botonSinAsfaltar)))
                                .addGap(41, 41, 41)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(botonPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(botonPedirViaje)
                            .addContainerGap()))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelMascota, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelEquipaje, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonSIequipaje)
                                .addGap(18, 18, 18)
                                .addComponent(botonNOequipaje))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonSImascota)
                                .addGap(18, 18, 18)
                                .addComponent(botonNOmascota)))
                        .addGap(76, 76, 76))))
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(labelInfoViaje)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 158, Short.MAX_VALUE)
                .addComponent(labelFormulario)
                .addGap(69, 69, 69))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 42, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelFormulario, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelInfoViaje, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ScrollPaneInfoViaje, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelCantPasajeros)
                            .addComponent(ComboBoxCantPax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(labelDistancia)
                        .addGap(18, 18, 18)
                        .addComponent(labelFecha))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(textDistancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(selectorFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelFecha1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonPeligrosa)
                            .addComponent(botonSinAsfaltar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(botonEstandar)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(botonPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonPedirViaje, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelMascota)
                            .addComponent(botonNOmascota)
                            .addComponent(botonSImascota))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelEquipaje)
                            .addComponent(botonNOequipaje)
                            .addComponent(botonSIequipaje))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBoxCantPax;
    private javax.swing.JScrollPane ScrollPaneInfoViaje;
    private javax.swing.JRadioButton botonEstandar;
    private javax.swing.JRadioButton botonNOequipaje;
    private javax.swing.JRadioButton botonNOmascota;
    private javax.swing.JButton botonPagar;
    private javax.swing.JButton botonPedirViaje;
    private javax.swing.JRadioButton botonPeligrosa;
    private javax.swing.JRadioButton botonSIequipaje;
    private javax.swing.JRadioButton botonSImascota;
    private javax.swing.JRadioButton botonSinAsfaltar;
    private javax.swing.ButtonGroup grupoBotonEquipaje;
    private javax.swing.ButtonGroup grupoBotonesMascota;
    private javax.swing.ButtonGroup grupoBotonesZona;
    private javax.swing.JLabel labelCantPasajeros;
    private javax.swing.JLabel labelDistancia;
    private javax.swing.JLabel labelEquipaje;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelFecha1;
    private javax.swing.JLabel labelFormulario;
    private javax.swing.JLabel labelInfoViaje;
    private javax.swing.JLabel labelMascota;
    private com.toedter.calendar.JDateChooser selectorFecha;
    private javax.swing.JTextArea textAreaInfoViaje;
    private javax.swing.JTextField textDistancia;
    // End of variables declaration//GEN-END:variables

 
    public JButton getButtonPagar()
    {
        return botonPagar;
    }
    
    public JButton getButtonPedirViaje()
    {
        return botonPedirViaje;
    }

    @Override
    public String getZona() {
        if(botonPeligrosa.isSelected())
            return "Peligrosa";
        else
            if(botonEstandar.isSelected())
                return "Estandar";
            else
                if(botonSinAsfaltar.isSelected())
                    return "Sin asfaltar";
                else
                    return null;
    }

    @Override
    public int getEquipaje() {
        if(botonSIequipaje.isSelected())
            return 1;
        else
            return 0;
    }

    @Override
    public int getMascota() {
       if(botonSImascota.isSelected())
            return 1;
        else
            return 0;
    }

    @Override
    public Integer getCantPax() {
        return Integer.parseInt((String)ComboBoxCantPax.getSelectedItem());
    }

    @Override
    public LocalDateTime getFecha() {
        Date selectedDate = selectorFecha.getDate();
        if (selectedDate != null) {
            Calendar calendar = Calendar.getInstance();
            calendar.setTime(selectedDate);
            int year = calendar.get(Calendar.YEAR);
            int month = calendar.get(Calendar.MONTH) + 1; // Los meses en Java comienzan desde 0, entonces se suma 1
            int day = calendar.get(Calendar.DAY_OF_MONTH);

            LocalDate localDate = LocalDate.of(year, month, day);
            LocalTime currentTime = LocalTime.now();
            LocalDateTime fecha = LocalDateTime.of(localDate, currentTime);
            return fecha;
        } else {
            return null;
        }
    }

    @Override
    public double getDistancia() {
     String text = textDistancia.getText();
        try {
            return Double.parseDouble(text);
        } catch (NumberFormatException e) {
            return -1;
        }
    }
    
    @Override
    public void appendDisplay(String mensaje){
        textAreaInfoViaje.append(mensaje);
    };
    
     @Override
    public void enablePagar(){
        botonPagar.setEnabled(true);
    };
    
     @Override
    public void disablePagar(){
        botonPagar.setEnabled(false);
    };
    
      @Override
    public void enablePedirViaje(){
        botonPedirViaje.setEnabled(true);
    };
    
     @Override
    public void disablePedirViaje(){
        botonPedirViaje.setEnabled(false);
    };
    
}
